name: Continuous Integration

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-onchain:
    name: build-onchain
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aiken-lang/setup-aiken@v1
        with:
          version: v1.1.12
      - run: aiken fmt --check
      - run: aiken check -D
      - run: aiken build
  build-offchain:
    name: build-offchain
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
      - run: bun install
        working-directory: offchain
      - run: bun test
